version: '3.8'
services:
  app:
    build: .
    container_name: module_achat_app
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: modul_achat_laravel_nginx
    depends_on:
      - app  # ← Nginx attend que PHP-FPM soit prêt
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  postgres:
    image: postgres:13
    container_name: modul_achat_postgres
    environment:
      POSTGRES_DB: projet_laravel
      POSTGRES_USER: toky
      POSTGRES_PASSWORD: toky
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
